name: Changelog

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  changelog:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Generate changelog
        uses: orhun/git-cliff-action@v4
        id: git-cliff
        with:
          config: .github/cliff.toml
          args: --verbose
        env:
          OUTPUT: CHANGELOG.md
          GITHUB_REPO: ${{ github.repository }}
          
      - name: Check if changelog was updated
        id: git-diff
        run: |
          if git diff --exit-code CHANGELOG.md; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi
          
      - name: Create Pull Request
        if: steps.git-diff.outputs.changed == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Configure git
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # Create branch and commit
          BRANCH="update-changelog-$(date +%s)"
          git checkout -b "$BRANCH"
          git add CHANGELOG.md
          git commit -m "chore: update CHANGELOG.md [skip ci]"
          git push origin "$BRANCH"
          
          # Create PR using GitHub CLI with auto-merge
          PR_URL=$(gh pr create \
            --title "chore: update CHANGELOG.md" \
            --body "## 📝 Automated Changelog Update
          
          This PR updates the CHANGELOG.md file with the latest commits.
          
          ### Changes Made:
          - Updated CHANGELOG.md with recent commits
          - Organized by conventional commit types
          - Added links to commits and issues
          
          ---
          *This PR was automatically generated by the changelog workflow.*" \
            --base main \
            --head "$BRANCH")
          
          # Enable auto-merge immediately
          gh pr merge "$PR_URL" --auto --squash